name: Hassfest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
